apiVersion: apps/v1
kind: Deployment
metadata:
  name: protools-flowable-wip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protools-flowable-wip
  template:
    metadata:
      labels:
        app: protools-flowable-wip
    spec:
      containers:
        - name: protools-flowable-wip
          image: mailinenguyen/protools-flowable:wip
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: protools-flowable-postgresql
                  key: postgres-password
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://protools-flowable-postgresql/
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-poc-pqv"
            - name: SPRING_RABBITMQ_PORT
              value: "15672"
            - name: SPRING_RABBITMQ_VIRTUEL_HOST
              value: "/"
            - name: SPRING_RABBITMQ_USERNAME
              value: "user"
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-poc-pqv
                  key: rabbitmq-password
            - name: RABBITMQ_LISTENER_SIMPLE_ACKNOWLEDGE
              value: "true"
            - name: RABBITMQ_LISTENER_SIMPLE_CONCURRENCY
              value: "1"
            - name: RABBITMQ_LISTENER_SIMPLE_PREFETCH
              value: "1"
            - name: RABBITMQ_LISTENER_SIMPLE_RETRY_ENABLED
              value: "false"
            - name: RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_ATTEMPTS
              value: "3"
            - name: RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_INTERVAL
              value: "10000"
            - name: RABBITMQ_LISTENER_SIMPLE_RETRY_MULTIPLIER
              value: "2"
