apiVersion: apps/v1
kind: Deployment
metadata:
  name: protools-flowable-wip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protools-flowable-wip
  template:
    metadata:
      labels:
        app: protools-flowable-wip
    spec:
      containers:
        - name: protools-flowable-wip
          image: mailinenguyen/protools-flowable:wip
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: protools-flowable-postgresql
                  key: postgres-password
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://protools-flowable-postgresql/
            - name: RABBITMQ_HOST
              value: "rabbitmq-poc-pqv"
            - name: RABBITMQ_PORT
              value: "15672"
            - name: RABBITMQ_VIRTUEL_HOST
              value: "/"
            - name: RABBITMQ_USERNAME
              value: "userTest"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-poc-pqv
                  key: rabbitmq-password
